### ISSUE TITLE
Respect $NO_COLOR variable

### ISSUE THREAD

**Issue by Sohalt** [BurntSushi/termcolor#13]
It would be cool for termcolor to respect the NO_COLOR "standard", i.e. when `$NO_COLOR` is set, termcolor should not colorize the output, at least in [auto](https://docs.rs/termcolor/1.0.4/termcolor/enum.ColorChoice.html#variant.Auto) mode. See https://no-color.org

**Comment by BurntSushi** [comment]
Having the discussion spread across two issues is really confusing. So I'm going to copy the comments from https://github.com/BurntSushi/ripgrep/issues/1186 into here:

---

[By @BurntSushi](https://github.com/BurntSushi/ripgrep/issues/1186#issuecomment-460375168):

I think I'm OK with this in principle. It should be implemented in [`termcolor`](https://github.com/BurntSushi/termcolor) as parts of its ["auto"](https://docs.rs/termcolor/1.0.4/termcolor/enum.ColorChoice.html#variant.Auto) mode.

I think I've historically not done this because it's not clear to me how widespread `NO_COLOR` usage actually is.

---

[By @Sohalt](https://github.com/BurntSushi/ripgrep/issues/1186#issuecomment-460424651):

Thanks, and sorry for not doing my research. I suspected ripgrep to use some library for colored terminal output and that would obviously be the better place to implement this. I've opened https://github.com/BurntSushi/termcolor/issues/13.
As for how widespread `NO_COLOR` usage is, I can't really say, but I don't see a big downside to not implementing it. The variable name is fairly specific and even if it is set, one can override it, i.e. turn on colors, on a per program basis.
You can probably close this issue, since it needs to be implemented in termcolor and the change will eventually show up in ripgrep, when dependencies are updated.

---

**Comment by BurntSushi** [comment]
> but I don't see a big downside to not implementing it

I do. If it doesn't garner wide appeal, then we're likely stuck with it forever. Once you add support for something like this, it is very difficult to remove. Of course, there is a chicken and egg problem here.

Part of my hesitation to do this is that there has been a long time work around to this, which is to set `TERM=dumb`, and is something that `termcolor` recognizes. The `NO_COLOR` FAQ mentions this, but I don't find the answer compelling.

**Comment by Sohalt** [comment]
Ok, I get what you are saying. So let's just leave this issue around and see, if there is enough demand? People in support of the issue can just use the 👍 reaction on the issue to express their interest.

**Comment by BurntSushi** [comment]
I added support for this in #24.

The next release of ripgrep should have this as well. It's currently on master: https://github.com/BurntSushi/ripgrep/commit/5a6e17fcc133f70f922a123483d0d5a158c041b0
