### ISSUE TITLE
Any way not to reset automatically with each set_color?

### ISSUE THREAD

**Issue by comfortablynick** [BurntSushi/termcolor#17]
I was testing some color output, matching against the output from another program. I can't get a match because this crate outputs the reset escape code `\x1B[0m` each time [`set_color()`](https://github.com/BurntSushi/termcolor/blob/6284c2e4100ce1999800d2eab39c964e1efc081c/src/lib.rs#L1159) is called. The output I'm trying to match does not reset before changing color.

Is there any way to avoid this, and allow the caller to be responsible for calling `reset()` as needed?

Thanks for the awesome crate.

**Comment by BurntSushi** [comment]
I don't think I can change the behavior of `set_color` here. It would be a breaking change. The idea is that `set_color` takes the given color specification---which specifies all possible settings---and then causes subsequent writes to reflect those settings. The only way to implement this is to call `reset` first.

I'm potentially open to adding a `set_color_without_reset` method, but I honestly question whether this is really necessary. What is the purpose of doing this?

**Comment by comfortablynick** [comment]
As I mentioned, I'm trying to match the output of another program ([todo.sh](https://github.com/todotxt/todo.txt-cli)). I am trying to set up tests to check that my Rust implementation matches the todo.sh output exactly. The only way I can do it is if I disable the reset.

I get the idea that `set_color` is designed to effect the color specification no matter what. Maybe what would be useful is a different type of method that simply "modifies" the current color setting. Kind of like what [ansi_term has](https://github.com/ogham/rust-ansi-term#combining-successive-coloured-strings), to allow the user to avoid sending unnecessary escape codes.

Unfortunately, in my testing, using ansi_term on strings is much slower than using termcolor on buffers, which is why I'm not using it.

**Comment by BurntSushi** [comment]
> As I mentioned, I'm trying to match the output of another program (todo.sh). I am trying to set up tests to check that my Rust implementation matches the todo.sh output exactly. The only way I can do it is if I disable the reset.

Yes, I know what you said, but it wasn't clear if this was the extent of it or not. So if I'm understanding correctly, you want this so that you can match the _byte for byte_ output of another program? If so, I'm not sure that's a use case worth facilitating in `termcolor`, and if that is truly a hard requirement, then you'd probably be better off just writing the escape sequences yourself. For example, `termcolor` could in theory change how certain colors are emitted via either [8-bit sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) or [24-bit true color sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit).

I don't feel too strongly about this. If you want to put up a PR, we can see how it looks.

> Unfortunately, in my testing, using ansi_term on strings is much slower than using termcolor on buffers, which is why I'm not using it.

You might consider filing a bug with `ansi_term` then. This doesn't seem right to me.

**Comment by comfortablynick** [comment]
> So if I'm understanding correctly, you want this so that you can match the _byte for byte_ output of another program? If so, I'm not sure that's a use case worth facilitating in `termcolor`, and if that is truly a hard requirement, then you'd probably be better off just writing the escape sequences yourself.

Yes, I suppose that's what I'm saying. I'm trying to set up an `assert_eq` in rust to compare the output of the shell script with the output of my program. I can't think of any way to do this without getting the escape sequences to match exactly.

You may be right, I might just need to write the 8-bit sequences myself as I did when playing with a C++ implementation.

If I do find a good solution by tweaking `termcolor` in a useful way, I'll definitely submit a PR.

Thanks!
