### ISSUE TITLE
Common crate for color and style types?

### ISSUE THREAD

**Issue by joshtriplett** [BurntSushi/termcolor#29]
There are several crates for styling text on the console, including `termcolor`, `console`, and `ansi_term`. There are also crates that want to deal with text styles generically without having to know which crate the user wants to use to render those styles; for instance, my own `colorparse` crate parses git configuration strings describing text styles and colors, and other configuration crates may want to support configuring such styles.

I think it might make sense to have a common crate that defines an enum for colors (identical to https://docs.rs/termcolor/1.1.0/termcolor/enum.Color.html and https://docs.rs/ansi_term/0.12.1/ansi_term/enum.Colour.html ), and a struct for text styles (booleans for attributes, optional foreground and background colors, URL for hyperlinks, etc). Ideally, those types could also include some useful builder functions, and perhaps the crate could also include a macro to construct constant instances of them.

Then, crates such as `colorparse` and other configuration libraries that want to handle colors and text styles could use those types, and crates such as `termcolor`, `console`, and `ansi_term` could provide a rendering API using those types (either by accepting those types as arguments, or by defining and implementing extension traits to add functions to those types).

I'm interested in helping to define and write such a crate, assuming there's interest in adopting it.

@ogham and I are looking to move `ansi_term` to a 1.0 API, and I'd be interested in incorporating such type changes as part of doing so. cc @pksunkara for `console` as well (we discussed this briefly on Zulip, and @pksunkara suggested discussing it via an issue here).

**Comment by BurntSushi** [comment]
> There are also crates that want to deal with text styles generically without having to know which crate the user wants to use to render those styles

To clarify, you're talking about just dealing with text styles as data objects rather than actually _applying_ those text styles?

It does seem like a nifty thing, but a little niche to me I think? I think the status quo is that everyone just defines their own types, and in the small number of cases where you need to inter-operate, you convert one object to the other. I guess that doesn't seem too bad to me, but maybe it's happening a lot more frequently than I think.

With that said, I am potentially open to this. I'd be happy to participate in the design process, wherever/whenever that may be. My main concerns would be:

* I _think_ this would probably add a new required dependency, or else otherwise it would be behind a feature, but that seems weird to me. `termcolor` has no dependencies in Unix environments today, so I generally consider the bar for adding a new dependency here to be pretty high.
* It seems like in addition to adding a new dependency, it would be a _public_ dependency. Which probably means that `termcolor` can't depend on it until it is at least 1.0 itself.
* Will this require breaking changes to termcolor? In general, my bar for this is also pretty high, particularly since `termcolor` itself may also be a public dependency. (Maybe it isn't often in practice though.) So I won't release a `termcolor 2.0` without really good reasons. I don't _think_ this would require breaking changes for `termcolor` though. Or at least, I can imagine a path that doesn't.
* Will the maintenance of this new common case be as approximately as conservative as I am with `termcolor`? (Stated differently, a new public dependency will require me to be _at least as_ liberal as that dependency.)

**Comment by pksunkara** [comment]
> so I generally consider the bar for adding a new dependency here to be pretty high

Could you explain your reasoning behind this? Sorry to ask but I am a bit curious. Some enums and/or structs will be moving from your lib to a dependency lib and it won't increase the binary size or decrease the performance (atleast I think so). So, why is there hesitance to add a new dep?

**Comment by joshtriplett** [comment]
> > There are also crates that want to deal with text styles generically without having to know which crate the user wants to use to render those styles
> 
> To clarify, you're talking about just dealing with text styles as data objects rather than actually _applying_ those text styles?

Right. So, for instance, serializing and deserializing styles, handling style configuration (such as git does), providing functionality equivalent to grep's `GREP_COLOR` environment variable, building data structures like "text with associated styles" or "text-based table cell with appropriate styles", implementing a configurable syntax highlighter that provides styled text back to an editor or renderer, and other tasks that don't actually involve rendering styled text to a terminal.

>     * I _think_ this would probably add a new required dependency, or else otherwise it would be behind a feature, but that seems weird to me. `termcolor` has no dependencies in Unix environments today, so I generally consider the bar for adding a new dependency here to be pretty high.

It wouldn't *have* to be required, but it would certainly be easier if it were. If you're using the types directly it'd be required; if you used it at "arms length" and translated from its types to yours you could get away with making it optional.

>     * It seems like in addition to adding a new dependency, it would be a _public_ dependency. Which probably means that `termcolor` can't depend on it until it is at least 1.0 itself.

It would indeed need to be a public dependency (since crates would depend on it for its types), but part of the point is to minimize the size of the "public dependency", from "all of one specific renderer" to "a set of common types supported by most renderers". And yes, it would need to be 1.0 before stable crates depend on it.

>     * Will this require breaking changes to termcolor? In general, my bar for this is also pretty high, particularly since `termcolor` itself may also be a public dependency. (Maybe it isn't often in practice though.) So I won't release a `termcolor 2.0` without really good reasons. I don't _think_ this would require breaking changes for `termcolor` though. Or at least, I can imagine a path that doesn't.

I can imagine ways to move to it without a breaking change; we can talk about that further when designing it.

>     * Will the maintenance of this new common case be as approximately as conservative as I am with `termcolor`? (Stated differently, a new public dependency will require me to be _at least as_ liberal as that dependency.)

I'm hoping that this crate would carefully define a set of types, and then almost never need further changes. Experiments like builders, which could potentially affect the API, should perhaps be in separate crates.

**Comment by BurntSushi** [comment]
> Could you explain your reasoning behind this? Sorry to ask but I am a bit curious.

I understand and appreciate the curiosity, but this debate has been waged for years and I am somewhat exhausted by it. More dependencies means more people to trust, more _units of code_ to review, more things to compile and more work on my part to ensure users of `termcolor` receive a certain level of quality that I wish to provide. I elaborated quite a bit on more specific issues here in my original comment. Those alone should give you an idea of what it means to take on a new public dependency.

> If there's another aspect of this that you're concerned about, we should work through that as part of designing the common crate and types.

SGTM. Just let me know where and when discussions are happening and I'll do my best to participate. My biggest concern here is probably going to maintenance to be honest.

**Comment by BurntSushi** [comment]
I'm going to close this issue for now since it seems like there hasn't been much movement here, but if things change, I'm happy to re-open!

**Comment by bestouff** [comment]
I have to agree with @joshtriplett on that one. I'm currently coding something with a plain terminal output as well as a full TUI. I have to duplicate colors and manually make them match because both crates I use don't have the same colors definitions.  
Not a showstopper, but not very nice either.
